import { StyleSheet } from '@react-pdf/renderer';

export const PDF_COLORS = {
  text: '#19191a',
  textSecondary: '#5c6570',
  textMuted: '#8a9199',
  border: '#e2e6ea',
  borderSubtle: '#eef0f2',
  surfaceMuted: '#f6f7f8',
  accent: '#0070F0',
  accentSoft: '#e8f2ff',
  success: '#0d7a4a',
  warning: '#9a6700',
  danger: '#b42318',
};

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 32,
    paddingHorizontal: 36,
    fontFamily: 'Helvetica',
    fontSize: 9,
    lineHeight: 1.45,
    color: PDF_COLORS.text,
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    paddingBottom: 12,
    gap: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    marginTop: 8,
    marginBottom: 10,
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metaItem: {
    width: '45%',
    marginBottom: 6,
  },
  metaLabel: {
    fontSize: 9,
    color: '#646568',
    marginBottom: 2,
  },
  metaValue: {
    fontSize: 10,
    color: '#19191a',
  },
  section: {
    marginTop: 16,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 9,
    color: '#646568',
    marginBottom: 8,
  },
  kvRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    paddingVertical: 6,
  },
  kvLabel: {
    color: '#646568',
    flex: 1,
  },
  kvValue: {
    fontWeight: 700,
    textAlign: 'right',
    flex: 1,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    paddingBottom: 4,
    marginBottom: 4,
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: 9,
    color: '#646568',
    fontWeight: 700,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    paddingVertical: 5,
  },
  tableCell: {
    flex: 1,
    fontSize: 9,
  },
  empty: {
    fontSize: 9,
    color: '#646568',
    fontStyle: 'italic',
  },
  cardBlock: {
    marginBottom: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 4,
  },
  teamHeader: {
    marginBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    paddingBottom: 14,
    gap: 6,
  },
  companyLogo: {
    width: 120,
    height: 24,
    objectFit: 'contain',
    marginBottom: 8,
  },
  companyWordmark: {
    fontSize: 18,
    fontFamily: 'Helvetica',
    fontWeight: 700,
    color: '#0B3D2E',
    marginBottom: 8,
  },
  teamReportTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: PDF_COLORS.text,
    marginTop: 2,
    lineHeight: 1.2,
  },
  rosterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  rosterCard: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 4,
  },
  rosterText: {
    flex: 1,
    gap: 2,
  },
  rosterName: {
    fontSize: 9,
    fontWeight: 600,
    color: PDF_COLORS.text,
  },
  rosterRole: {
    fontSize: 8,
    color: PDF_COLORS.textSecondary,
    fontWeight: 400,
  },
  efficiencyHeroRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'stretch',
  },
  efficiencyHeroCard: {
    width: '36%',
    minHeight: 118,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 8,
    paddingTop: 16,
    paddingBottom: 14,
    paddingHorizontal: 14,
    backgroundColor: PDF_COLORS.surfaceMuted,
    justifyContent: 'flex-start',
  },
  efficiencyHeroValue: {
    fontSize: 36,
    fontWeight: 700,
    color: PDF_COLORS.text,
    lineHeight: 1.05,
    marginBottom: 8,
  },
  efficiencyHeroLabel: {
    fontSize: 10,
    fontWeight: 500,
    color: PDF_COLORS.textSecondary,
    lineHeight: 1.3,
    marginBottom: 6,
  },
  efficiencyHeroStatus: {
    fontSize: 9,
    color: PDF_COLORS.success,
    fontWeight: 600,
    marginTop: 2,
    lineHeight: 1.3,
  },
  efficiencySupportGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignContent: 'flex-start',
  },
  efficiencySupportCard: {
    width: '31%',
    minWidth: 90,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 6,
    padding: 10,
    backgroundColor: '#fafafa',
  },
  efficiencySupportValue: {
    fontSize: 20,
    fontWeight: 700,
    color: PDF_COLORS.text,
    lineHeight: 1.15,
    marginBottom: 4,
  },
  efficiencySupportLabel: {
    fontSize: 9,
    fontWeight: 500,
    color: PDF_COLORS.textSecondary,
    lineHeight: 1.25,
  },
  individualGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  individualCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 8,
    padding: 10,
    marginBottom: 4,
  },
  individualCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  individualEfficiencyRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    marginTop: 4,
    marginBottom: 8,
  },
  individualEfficiencyValue: {
    fontSize: 24,
    fontWeight: 700,
    color: PDF_COLORS.text,
    lineHeight: 1.1,
  },
  individualEfficiencyCaption: {
    fontSize: 9,
    fontWeight: 500,
    color: PDF_COLORS.textSecondary,
  },
  individualMetricsRow: {
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.borderSubtle,
    paddingTop: 6,
    gap: 4,
  },
  individualMetricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  individualMetricLabel: {
    fontSize: 8,
    color: PDF_COLORS.textMuted,
    fontWeight: 400,
  },
  individualMetricValue: {
    fontSize: 8,
    color: PDF_COLORS.text,
    fontWeight: 600,
  },
  trendGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  trendGridItem: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 8,
    padding: 10,
    marginBottom: 4,
  },
  trendDelta: {
    fontSize: 8,
    color: '#646568',
    textAlign: 'right',
  },
  teamReportDates: {
    fontSize: 11,
    fontWeight: 500,
    color: PDF_COLORS.textSecondary,
    marginTop: 2,
  },
  sectionBlock: {
    marginTop: 14,
    marginBottom: 6,
  },
  sectionHeading: {
    fontSize: 9,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: PDF_COLORS.textSecondary,
    marginBottom: 8,
  },
  sectionLead: {
    fontSize: 9,
    color: '#646568',
    marginBottom: 6,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  kpiCard: {
    width: '47%',
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 6,
    padding: 10,
    backgroundColor: '#fafafa',
  },
  kpiValue: {
    fontSize: 24,
    fontWeight: 700,
    color: '#19191a',
    marginBottom: 4,
  },
  kpiLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: '#3b3b3d',
  },
  kpiComparison: {
    fontSize: 8,
    color: '#646568',
    marginTop: 4,
  },
  kpiDescription: {
    fontSize: 8,
    color: '#646568',
    marginTop: 2,
  },
  digestSummary: {
    fontSize: 9,
    color: PDF_COLORS.textSecondary,
    marginBottom: 4,
    lineHeight: 1.5,
    fontWeight: 400,
  },
  digestColumns: {
    flexDirection: 'row',
    gap: 10,
  },
  digestTable: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 6,
    overflow: 'hidden',
  },
  digestTableTitle: {
    fontSize: 9,
    fontWeight: 700,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#f3f3f4',
    color: '#3b3b3d',
  },
  digestTableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    backgroundColor: '#f8f8f8',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  digestTableHeaderCell: {
    flex: 1,
    fontSize: 8,
    fontWeight: 700,
    color: '#646568',
  },
  digestTableHeaderCellRight: {
    width: 56,
    fontSize: 8,
    fontWeight: 700,
    color: '#646568',
    textAlign: 'right',
  },
  digestTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#efefef',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  digestTableCell: {
    flex: 1,
    fontSize: 8,
    color: '#19191a',
  },
  digestTableCellRight: {
    width: 56,
    fontSize: 8,
    color: '#19191a',
    textAlign: 'right',
    fontWeight: 600,
  },
  tableHeaderMuted: {
    flexDirection: 'row',
    backgroundColor: '#f3f3f4',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  tableRowMuted: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#efefef',
  },
  attentionPersonCol: {
    width: '34%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    fontSize: 8,
  },
  attentionCol: {
    width: '30%',
    fontSize: 8,
  },
  attentionSmallCol: {
    width: '12%',
    fontSize: 8,
  },
  attentionPersonName: {
    fontSize: 8,
    flex: 1,
  },
  avatar: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  avatarFallback: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#e6e6e6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    fontSize: 7,
    fontWeight: 700,
    color: '#646568',
  },
  workloadCol: {
    width: '46%',
    fontSize: 8,
    fontWeight: 500,
    color: PDF_COLORS.text,
  },
  workloadSmallCol: {
    width: '18%',
    fontSize: 8,
    color: PDF_COLORS.textSecondary,
  },
  workloadToneDanger: {
    color: PDF_COLORS.danger,
    fontWeight: 600,
  },
  workloadToneWarning: {
    color: PDF_COLORS.warning,
    fontWeight: 600,
  },
  workloadToneSuccess: {
    color: PDF_COLORS.success,
    fontWeight: 600,
  },
  deliveryRiskHeader: {
    flexDirection: 'row',
    backgroundColor: PDF_COLORS.surfaceMuted,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
    marginBottom: 2,
  },
  deliveryRiskHeaderCell: {
    fontSize: 7,
    fontWeight: 600,
    color: PDF_COLORS.textSecondary,
  },
  deliveryRiskRow: {
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.borderSubtle,
    alignItems: 'flex-start',
  },
  deliveryRiskColIssue: {
    width: '11%',
    fontSize: 7,
    fontWeight: 600,
    color: PDF_COLORS.text,
  },
  deliveryRiskColOwner: {
    width: '14%',
    fontSize: 7,
    color: PDF_COLORS.text,
  },
  deliveryRiskColStatus: {
    width: '12%',
    fontSize: 7,
    color: PDF_COLORS.text,
    fontWeight: 500,
  },
  deliveryRiskColAge: {
    width: '8%',
    fontSize: 7,
    color: PDF_COLORS.textSecondary,
  },
  deliveryRiskColReason: {
    width: '18%',
    fontSize: 7,
    color: PDF_COLORS.text,
    lineHeight: 1.35,
  },
  deliveryRiskColPath: {
    width: '37%',
    fontSize: 6.5,
    lineHeight: 1.35,
    color: PDF_COLORS.textMuted,
  },
  trendCard: {
    borderWidth: 1,
    borderColor: '#e6e6e6',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  trendHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  trendLabel: {
    fontSize: 9,
    fontWeight: 600,
    color: PDF_COLORS.textSecondary,
  },
  trendValue: {
    fontSize: 11,
    fontWeight: 700,
    color: PDF_COLORS.text,
    textAlign: 'right',
  },
  trendNoChart: {
    fontSize: 8,
    color: '#646568',
    fontStyle: 'italic',
  },
});
