import type { WorkflowProfileMapping } from './types';

export const DEFAULT_WORKFLOW_MAPPINGS: WorkflowProfileMapping[] = [
  { projectKey: 'UX', profileId: 'ux' },
  { projectKey: 'UX', issueType: 'Design Improvement', profileId: 'design_review' },
  { projectKey: 'WS', issueType: 'Skin', profileId: 'wskins_skin' },
  { projectKey: 'WS', issueType: 'Sub-task', profileId: 'wskins_subtask' },
  { projectKey: 'AGTC', issueType: 'Provider', profileId: 'agtc_provider' },
  { projectKey: 'AGTC', profileId: 'design_review' },
  { projectKey: 'AIVA', profileId: 'design_review' },
  { projectKey: 'AGP', issueType: 'Story', profileId: 'agp_development' },
  { projectKey: 'AGP', issueType: 'Dev Internals', profileId: 'agp_internal' },
  { projectKey: 'AGP', profileId: 'classic_review' },
  { projectKey: 'ADF', issueType: 'Incident', profileId: 'adf_incident' },
  { projectKey: 'ADF', profileId: 'dev_qa_release' },
  { projectKey: 'PRD', issueType: 'Direct Request', profileId: 'prd_phased' },
  { projectKey: 'PRD', issueType: 'Epic', profileId: 'prd_phased' },
  { projectKey: 'PRD', issueType: 'Story', profileId: 'prd_phased' },
  { projectKey: 'PRD', issueType: 'Improvement', profileId: 'prd_discovery' },
  { projectKey: 'PRD', issueType: 'New Feature', profileId: 'prd_discovery' },
  { projectKey: 'PRD', issueType: 'Task', profileId: 'prd_task' },
  { projectKey: 'PRD', issueType: 'Sub-task', profileId: 'prd_task' },
  { projectKey: 'PRD', profileId: 'product_handover' },
  { projectKey: 'ARCH', profileId: 'governance' },
  { projectKey: 'CRC', profileId: 'editorial' },
  { projectKey: 'CIT', issueType: 'Purchase Request', profileId: 'cit_purchase' },
  { projectKey: 'CIT', issueType: 'Security Patch', profileId: 'cit_security_patch' },
  { projectKey: 'CIT', profileId: 'cit_delivery' },
];
